### ISSUE TITLE
investigate tilage

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-selector#435]
**What's wrong**
- need to determine if mccc and neccc treat tilage the same

**What done looks like**
- mccc increases drainage class by 2 values but no more than moderately well drained if tilage exists
- neccc logic is what existed in the code
- i will get sccc logic
- need to verify how neccc is handling tilage in the code

**Where the changes need to be made**
- SoilCondition.js

**Comment by Adamws33** [comment]
the NECCC looks like it only adjusts the tiling if one or more of the first 3 soil conditions are selected and it increases the selection by one.  Since the selection is done by string there is a big if else statement in SoilConditions to handle this.  I could mimic this for the MCCC so that it will move 2 steps. or we could consider how we are setting this data and potentially move to a number system and then it could be simpler to just add 1 or 2 to the value and then use the numerical value to determine which options are selected.  or something similar.

**Comment by mikahpinegar** [comment]
also the tiling toggle button is broken right now

**Comment by mikahpinegar** [comment]
yeah after looking at it, all the logic for tilage SoilCcondition.js should be moved to SoilDrainage.js and it should be updating soilDataRedux instead of drainSet
