### ISSUE TITLE
numerical graphics issue in cc description window

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/dst-selector#443]
<img width="748" alt="image" src="https://github.com/precision-sustainable-ag/dst-selector/assets/49722541/027ad273-3f64-47d6-a0aa-c8ce7545eff4">
Cover Crop description window in the selector has graphical bugs. Data for numerics like seeding rate is in pillbox rating format

**Comment by mikahpinegar** [comment]
this is probably happening because of missing data. is something doesn't have a value it defaults to an empty pill box which is not the ideal behavior

**Comment by mikahpinegar** [comment]
Notes for the SCCC info sheet from victoria (Clover, Balansa): 

- [ ] Basic Agronomics 
- Dry Matter Min and Max should be next to each other and a number, not a pillbox; 
- [ ] Environmental Tolerances 
- mostly missing, though they are populated in Airtable (example: shade tolerance);
-  physiographic region doesn't need listed in this section, imo; 
- [ ] Growth 
- the notes section makes a mess of the rest of the formatting in this section: 
- [ ] Planting 
- seeding rates should be numbers, not pillboxes; 
- ditto for planting depths (which have been in Airtable since last fall); 
- [ ] Planting and growth windows 
- I would not include this in the info sheet in this format, or at least get rid of 'average frost' range; 
- [ ] Taxonomy 
- If this section stays, it needs to be at the top, and it needs to nix 'internal' data like Itis TSN; 
- [ ] Weeds 
- the hard seed/seed dormancy should be a pillbox
